[package]
name = "vertex-cover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
star = { git = "https://github.com/thm-mni-ii/StaR" }
rand = "0.8.4"
